name: flutter_laboratornaya_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
     - assets/images/first.jpg
     - assets/images/second.jpg
     - assets/images/3.jpg
     - assets/images/four.jpg
     - assets/images/five.jpg
     - assets/images/six.jpg
     - assets/images/seven.jpg
     - assets/images/8.jpg

fonts:
    - family: Michroma
      fonts:
        - asset: assets/fonts/Michroma-Regular.ttf